@url=http://localhost:3333

###
POST {{url}}/daily-diet/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@email.com"
}

###
POST {{url}}/daily-diet/meals
Content-Type: application/json

{
    "title": "Salada",
    "description": "Salada básica",
    "date": "2023-03-30",
    "time": "12:15",
    "isOnDiet": true
}

###
POST {{url}}/daily-diet/meals
Content-Type: application/json

{
    "title": "X Tudo",
    "description": "Xis completo",
    "date": "2023-03-30",
    "time": "16:15",
    "isOnDiet": false
}

###
GET {{url}}/daily-diet/meals
Content-Type: application/json

###
GET {{url}}/daily-diet/meals/9f86ebf8-6642-412e-8eb4-6f42a6b3c13f
Content-Type: application/json

###
PUT {{url}}/daily-diet/meals/9f86ebf8-6642-412e-8eb4-6f42a6b3c13f
Content-Type: application/json

{
    "title": "X Tudo",
    "description": "Xis completo de salada",
    "date": "2023-03-30",
    "time": "16:15",
    "isOnDiet": true
}

###
DELETE {{url}}/daily-diet/meals/9f86ebf8-6642-412e-8eb4-6f42a6b3c13f
Content-Type: application/json